using System.Runtime.CompilerServices;
using SpaceWarp;
using SpaceWarp.API.Assets;
using SpaceWarp.API.Configuration;
using SpaceWarp.API.Game;
using SpaceWarp.API.Game.Extensions;
using SpaceWarp.API.Game.Messages;
using SpaceWarp.API.Loading;
using SpaceWarp.API.Logging;
using SpaceWarp.API.Lua;
using SpaceWarp.API.Lua.UI;
using SpaceWarp.API.Mods;
using SpaceWarp.API.Mods.JSON;
using SpaceWarp.API.Parts;
using SpaceWarp.API.UI;
using SpaceWarp.API.UI.Appbar;
using SpaceWarp.API.UI.Settings;
using SpaceWarp.API.Versions;
using SpaceWarp.Modules;
using SpaceWarp.Patching.LoadingActions;

[assembly: TypeForwardedTo(typeof(AssetManager))]
[assembly: TypeForwardedTo(typeof(BepInExConfigEntry))]
[assembly: TypeForwardedTo(typeof(BepInExConfigFile))]
[assembly: TypeForwardedTo(typeof(ConfigValue<>))]
[assembly: TypeForwardedTo(typeof(EmptyConfigFile))]
[assembly: TypeForwardedTo(typeof(IConfigEntry))]
[assembly: TypeForwardedTo(typeof(IConfigFile))]
[assembly: TypeForwardedTo(typeof(JsonConfigEntry))]
[assembly: TypeForwardedTo(typeof(JsonConfigFile))]
[assembly: TypeForwardedTo(typeof(Loading))]
[assembly: TypeForwardedTo(typeof(SaveLoad))]
[assembly: TypeForwardedTo(typeof(BaseLogger))]
[assembly: TypeForwardedTo(typeof(BepInExLogger))]
[assembly: TypeForwardedTo(typeof(ILogger))]
[assembly: TypeForwardedTo(typeof(LogLevel))]
[assembly: TypeForwardedTo(typeof(UnityLogSource))]
[assembly: TypeForwardedTo(typeof(LuaUITK))]
[assembly: TypeForwardedTo(typeof(LuaMod))]
[assembly: TypeForwardedTo(typeof(SpaceWarpInterop))]
[assembly: TypeForwardedTo(typeof(SpaceWarpLuaAPIAttribute))]
[assembly: TypeForwardedTo(typeof(DependencyInfo))]
[assembly: TypeForwardedTo(typeof(ModInfo))]
[assembly: TypeForwardedTo(typeof(SpecVersion))]
[assembly: TypeForwardedTo(typeof(SupportedVersionsInfo))]
[assembly: TypeForwardedTo(typeof(VersionCheckType))]
[assembly: TypeForwardedTo(typeof(BaseKspLoaderSpaceWarpMod))]
[assembly: TypeForwardedTo(typeof(BaseSpaceWarpPlugin))]
[assembly: TypeForwardedTo(typeof(GlobalModDefines))]
[assembly: TypeForwardedTo(typeof(ISpaceWarpMod))]
[assembly: TypeForwardedTo(typeof(PluginList))]
[assembly: TypeForwardedTo(typeof(SpaceWarpErrorDescription))]
[assembly: TypeForwardedTo(typeof(SpaceWarpPluginDescriptor))]
[assembly: TypeForwardedTo(typeof(Colors))]
[assembly: TypeForwardedTo(typeof(VersionUtility))]
[assembly: TypeForwardedTo(typeof(DescriptorLoadingAction))]
[assembly: TypeForwardedTo(typeof(ModLoadingAction))]
[assembly: TypeForwardedTo(typeof(ModuleManager))]
[assembly: TypeForwardedTo(typeof(SpaceWarpModule))]
[assembly: TypeForwardedTo(typeof(AddressableAction<>))]
[assembly: TypeForwardedTo(typeof(SpaceWarpPlugin))]
[assembly: TypeForwardedTo(typeof(PartProviderExtensions))]
[assembly: TypeForwardedTo(typeof(VesselVehicleExtensions))]
[assembly: TypeForwardedTo(typeof(StateChanges))]
[assembly: TypeForwardedTo(typeof(StateLoadings))]
[assembly: TypeForwardedTo(typeof(Vehicle))]
[assembly: TypeForwardedTo(typeof(AppBarInterop))]
[assembly: TypeForwardedTo(typeof(Appbar))]
[assembly: TypeForwardedTo(typeof(AppbarMenu))]
[assembly: TypeForwardedTo(typeof(ModsPropertyDrawers))]
[assembly: TypeForwardedTo(typeof(MainMenu))]
[assembly: TypeForwardedTo(typeof(Skins))]